### ISSUE TITLE
Make public H5P list page

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#269]
Generate an optional page/chapter that just includes all of the visible H5P activities for a given book (would function like the glossary list tool, basically, but for H5P activities). The page could display as a back matter type, or as a published page at a consistent path for all books. Additionally, we could consider adding a menu column to the H5P list (would require forking the H5P plugin) that let book admins add/remove individual activities from the overall list (as can be done with glossary terms). 
![Screenshot from 2020-01-24 13-15-22](https://user-images.githubusercontent.com/13485451/73096927-9ba78c00-3eab-11ea-950a-9ca07b1a6ed9.png)

**Comment by hughmcguire** [comment]
👍

**Comment by SteelWagstaff** [comment]
1. Create php template that displays activity title and H5P shortcode for all H5P activities (i.e. 
```
Activity Name 1
[h5p id="1"]
Activity Name 2
[h5p id="2"]
```

2. Doesn't need admin link, but should have reliable URL (i.e. h5plist.php or just h5plist). 
3. If possible, can this display page lazy load on scroll (to help performance for books/pages with lots of activities?

**Comment by SteelWagstaff** [comment]
H5P activity lists will be generated for each book at a predictable path: `https://network.domain/booktitle/h5p-listing/`, e.g. https://integrations.pressbooks.network/steelstest/h5p-listing/

**Comment by mcgratay** [comment]
I was able to determine that the h5p listing display issues were because of the activities and not because of the list itself. There are some implications that has for the listing page, i.e. that **when one element cannot display, it somehow affects whether or not other h5p elements on the page display**, regardless of whether those other elements have the same technical issues. More important to note for support than for development. 

**My only suggestions would be:** 

1) to make the h5p listing page consistent with the cloning behavior. Currently, all H5P elements a user has created will display in the list, but only those in public chapters can be cloned

2) to remove access to the H5P listing page when the H5P plugin is turned off. Even though the H5P activities don't exist in the book or back end anymore, the list still "displays" the activity, as a plain text shortcode: 
![Screen Shot 2020-02-24 at 3 56 01 PM](https://user-images.githubusercontent.com/39064028/75190371-29320200-571e-11ea-9692-968cefbd5f7d.png)

**Behavior to note:** 
- H5P list cannot be imported via HTML
- H5P list still exists for books which have never used H5P or activated the plugin

**Comment by SteelWagstaff** [comment]
Two proposed refinements:
1. Display the H5P listing page if and only if the H5P plugin is active && at least one H5P activity exists in the book
2. Allow ALL activities in a book to be cloned by adding support H5P listing page to the API-based HTML importer. If a user chooses to import an html page and selects `https://network.url/testbook/h5p-listing` -- the cloning routine should fetch and clone all of the H5P activities on that page/in that book to the target.
