### ISSUE TITLE
Allow users to style glossary terms in PDF exports

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/ideas#327]
### Feature Description

This is based on ZD ticket 150 (this is only for reference), and the request comes from Mt Hood Community College (MHCC).

Right now, special styling for glossary items is not available for PDFs. In the webbook format, our code structure is set up so that individual Glossary terms are wrapped in `<button>` elements with the class `.glossary`. When we generate the XHTML document that our PDF exports are based on, this button element is not included and glossary terms are totally unmarked. To fix this, we should consider turning the button into a `<span>` element with class `.glossary` for the XHTML and PDF exports.

### Feature Use Case

For accessibility purposes and otherwise, the lack of customizable styling for glossary terms in PDF is inconvenient. PDFs are possibly the most frequently used offline version of textbooks, and it would be nice if glossary terms could be fixed to accommodate for this.

### Other Notes

Even if there is not an option to have a glossary feature which exactly resembles that of the webbook, a work-around would suffice as well.

**Comment by ricardopressbooks** [comment]
PRs:
- https://github.com/pressbooks/pressbooks/pull/2025
- https://github.com/pressbooks/pressbooks-book/pull/713

**Comment by SteelWagstaff** [comment]
@ricardopressbooks & @ho-man-chan Glossary terms now have a span with .glossary-term applied to them in the XHTML, which is good. However, https://github.com/pressbooks/pressbooks-book/pull/713 adds unwanted styling to the glossary terms in PDF exports and puts it in an unexpected location within Buckram. Rather than adding a hard coded colour value #541600;, we should instead consider simply bolding the term (font-weight) for XHTML/PDF exports. The SCSS rule that does this should not be placed in TOC (table of contents) -> generic, but in the appropriate location, something like: https://github.com/pressbooks/pressbooks-book/tree/5593792a31d0c0b1a1ca82711aeff9c25d8066c8/packages/buckram/assets/styles/components/specials

**Comment by ricardopressbooks** [comment]
Thank you for review it Steel. 
I submitted a new PR with required changes: https://github.com/pressbooks/pressbooks-book/pull/716. For testing, Check in Appareance -> Custom Styles -> PDF and confirm you have `.glossary-term` class with bold style. Also, export a book with glossary term and confirm the style for those.
Also, you should add custom style for .glossary-term class in "Your PDF Style" section and check if PDf have that custom style for glossary term.

**Comment by SteelWagstaff** [comment]
Glossary terms now have a span with class .glossary-term and have a default font-weight of bold in webbooks (once the stylesheet is reset) and export formats.
