### ISSUE TITLE
[Research] Simple plugin to add necessary metadata for Presbooks Directory

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/ideas#346]
Research about Books API Interception in Presbooks Plugin in order to add necessary fields from a separate plugin. In that way we could have compatibility with Dierctory Fetcher without install the latest PB version. Also, it could be useful if we need to update the API for PB Directory.

- [x] Review Dac's previous notes/work in https://github.com/pressbooks/pb-api/issues/3
- [ ] Research what would be needed to move Pressbooks API entirely out of Pressbooks core and into a standalone plugin
- [ ] Produce single document with a recommendation/proposal (pros/cons/gotchas)

**Comment by SteelWagstaff** [comment]
Compare with https://github.com/pressbooks/pb-api/issues/3?

**Comment by dac514** [comment]
> Compare with [pressbooks/pb-api#3](https://github.com/pressbooks/pb-api/issues/3)?

Before Pressbooks had API V2, Brad from BcCampus had contributed API V1.
V2 was built on WordPress REST API. 
V1 was not (such a thing did not exist.) Here is the PR that introduced API V1 in 2014:
https://github.com/pressbooks/pressbooks/pull/70

To make room for V2, Brad's code was moved out of core into `pb-api`.
The idea was that we might need to support V1 if BcCampus still needed it.
The issue you linked contains code snippets if someone really wanted to wedge V1 back into Pressbooks.
Lucky for us, everyone started using V2 (and we never finished)

`pb-api` had more to do with trying to simplify the code base because we didn't want two totally different REST APIs in core. It's an archive. A backup. Nothing more, really. I don't think it will help you in your research.

**Comment by SteelWagstaff** [comment]
I've archived the pb-abi repo and am closing this issue. FYI @richard015ar and @cmurtagh
