### ISSUE TITLE
Make all child themes 'shape shifter' compatible

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/ideas#431]
The 'shape shifter' font selection theme option is popular among users of McLuhan and Malala. We should add support for this to all supported McLuhan child themes.

See https://pressbooks.org/blog/2019/09/24/font-selector-theme-option/ + https://github.com/pressbooks/pressbooks/blob/dc7a74eaa0a396b6b79e8ced95ed691a0a9628e2/inc/class-styles.php#L664-L666 + https://github.com/pressbooks/pressbooks/pull/2020

TODO
- [x] open PRs in all theme repos adding support for shapeshifter font stack
- [x] Test theme options in web, EPUB, and PDF export for all themes. See https://github.com/pressbooks/ideas/issues/431#issuecomment-1372811089
- [ ] Update docs

**Comment by SteelWagstaff** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/ideas/431?planning-poker) with Zenhub @arzola @cmurtagh @fdalcin @ho-man-chan @MichelleWeremczuk @richard015ar @tw77

**Comment by SteelWagstaff** [comment]
All themes should now include support for shapeshifter. To test:
1. Apply the desired theme. 
2. View the webbook and confirm that headings and body text use the expected typeface
3. Produce an EPUB and PDF export and confirm that headings and body text use the expected typeface
4. Go to theme options and check web options. You should be able to select an option from the heading font and body font drop down selectors. Change each of these and confirm that they are updated as expected in the webbook.
5. Change them back to the default and confirm that the webbook uses the default typefaces for the theme again.
6. Go to EPUB options and change the header/body font. Save changes & produce a new EPUB export. Check to see that the EPUB includes and uses the designated typefaces as expected.
7. Go to PDF options and change the header/body font. Save changes & produce a new PDF export. Check to see that the PDF files displays the selected typefaces as expected.
8. Repeat for each theme.

**Comment by SteelWagstaff** [comment]
@tw77 this should be ready for testing. All themes on integrations should be tested, except for McLuhan and Malala, which already supported the feature. Happy to answer any questions or help in any way you think useful.

**Comment by tw77** [comment]
Using Adunis, when I select one font as the Header Font and a different font as the Body Font, the font for headings is also used for body text within **tables** and **textboxes**.

For example, here’s how Header Font = Cormorant Garamond and Body Font = Roboto correctly appear:

<img width="519" alt="Screenshot 2023-01-10 at 10 27 06 AM" src="https://user-images.githubusercontent.com/44182629/211632513-8ed1e70e-47d3-4f60-8a9d-cc8adaf22b89.png">

Here’s how they appear inside a textbox. Cormorant Garamond is being applied to the body text, not just the headings:

<img width="502" alt="Screenshot 2023-01-10 at 10 26 43 AM" src="https://user-images.githubusercontent.com/44182629/211632442-1393a231-c06b-4aa7-94eb-06580c592c89.png">

Note: the body text being smaller when it appears at the bottom of this textbox is a separate topic, since this also occurs when using default typefaces. This difference in size is observable in textboxes across themes, and seems to be caused by the `<p>` tag being applied to body text after a heading tag has been used, but not before. I can look into this and file if it isn't a known issue.

Using Andreesen, when I do the same thing of selecting one font as the Header Font and a different font as the Body Font, the font for headings is also rendered as the body font within **textboxes**. However, **tables** render fonts as expected. I can test for this on other themes.

**Comment by tw77** [comment]
Tested a webbook with all themes for this issue where selected Header Fonts are used instead of selected Body Fonts in textboxes and/or tables.

**Textboxes and tables affected:** Adunis, Bradbury, Graham

**Textboxes affected, tables fine:** Asimov, Baker, Christie

**Textboxes fine, tables affected:** Atwood

**Not affected by this issue:** Austen, Bronte, Bukowski, Clarke, Cleary, Dillard, Donham, Jacobs, Kolbert, Leonard, Lewis, Malala, McLuhan

From initial tests, this is consistent with PDF and EPUB output for each theme.

**Comment by tw77** [comment]
I notice that with Cleary theme in web, PDF and EPUB formats, h1s and h2s use a distinct font-family that is modifiable by selecting a Header Font from Theme Options, but h3s, h4s, h5s and h6s use the same font-family as body text. This is true when using theme defaults as well. As a result, whichever font is selected as the Body Font is applied to h3s, h4s, h5s and h6s instead of the selected Header Font.

**Comment by tw77** [comment]
^ above Cleary question clarified by Dalcin as preserving existing theme behaviour. Approach to themes like Cleary to be discussed with Steel but current approach could work for this ticket.

**Comment by tw77** [comment]
Lewis theme PDF and EPUB exports use the font-family of the specified Body Font for all headers (h1 to h6) instead of the specified Header Font. Webbook uses the Header font for headers as expected.

**Comment by tw77** [comment]
Otherwise, all themes including selected fonts as expected in web, PDF, EPUB output, with the ability to revert to default typefaces.

**Comment by SteelWagstaff** [comment]
Here's my summary of issues that should be solved:
1. With shapeshifter, body text inside of textboxes and tables is not always the same as body text elsewhere in the book. The use of 'header' text for body text within textboxes and tables can be observed in the webbook, EPUB, and PDF exports. It occurs for the following themes:
**Textboxes and tables affected:** Adunis, Bradbury, Graham
**Textboxes only:** Asimov, Baker, Christie
**Tables only:** Atwood
2. In the cleary theme, choosing the 'header' font with shapeshifter has no effect on h3, h4, h5, and h6 elements (in webbook, EPUB, or PDF exports). However, these elements don't use the same font as H1 and H2 elements in the 'regular' version of these theme (i.e. without shapeshifter). 
3. In the Lewis theme, choosing a header font for PDF and EPUB exports with shapeshifter has no effect. Headers display in the selected 'body-font' for these export formats. Shapeshifter works as expected in the web book. however, for both header and body fonts.

My suspicion is that each of these can be explained by the theme's use (or misuse) of Buckram variables. To be explored further with a developer.

**Comment by SteelWagstaff** [comment]
@tw77 We believe that the following are fixed and ready for testing:
1. textboxes and tables should now display body text as expected in Adunis, Bradbury, Graham
2. textboxes should now display body text as expected in Asimov, Baker, Christie
3. tables should now display body text as expected in Atwood
4. H3, H4, H5, and H6 elements should now display the chosen header font in Cleary (before and after shapeshifter is applied and in all formats: web, epub, and PDF)
5. All headings should now be updated as expected in EPUB and PDF exports in Lewis (before and after shapeshifter is applied and in formats: web, epub, and PDF)

Changes are still being autodeployed but should be ready for testing in next 15 minutes
